version: '3'
services:

  nxpod:
    image: eu.gcr.io/nxpod-core-dev/build/nxpod-k3s:${VERSION:-latest}
    privileged: true
    # tmpfs:
    #   - /run
    #   - /var/run
    #   - /var/nxpod/workspaces
    volumes:
      - ./values:/values
      # - ./certs:/certs
    ports:
      - 443:443
      - 80:80
    environment:
      - DOMAIN=${DOMAIN}
      - DNSSERVER=${DNSSERVER:-}
      - NXPOD_CHART_VERSION=${NXPOD_CHART_VERSION:-}
