# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

packages:
  - name: helm
    type: generic
    srcs:
      - "**/*.yaml"
      - "**/*.tpl"
      - "secrets/**/*"
      - "config/**/*"
    argdeps:
      - version
      - imageRepoBase
    config:
      commands:
        # set values
        - ["yq", "w", "-i", "Chart.yaml", "version", "${version}"]
        - ["yq", "w", "-i", "values.yaml", "version", "${version}"]
        - ["yq", "w", "-i", "values.yaml", "imagePrefix", "${imageRepoBase}"]
        # prepare chart
        - ["sh", "-c", "ls -A | grep -v BUILD.yaml | grep -v original_files > original_files.txt"]
        - ["mkdir", "nxpod"]
        - ["sh", "-c", "mv $(cat original_files.txt) nxpod"]
        # pack up
        - ["helm", "dependency", "build", "nxpod"]
        - ["helm", "package", "nxpod", "--destination", "."]
        - ["rm", "-rf", "yq", "nxpod", "BUILD.yaml", "original_files.txt"]
