# Copyright (c) 2022 Nxpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pod/status
  verbs:
  - get
- apiGroups:
  - workspace.nxpod.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspace.nxpod.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - workspace.nxpod.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
