# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{- $comp := .Values.components.imageBuilder -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}

{{- define "registry-name" -}}
{{- $comp := .comp -}}
{{- $ := .root -}}
{{- if eq $comp.registry.name "builtin" -}}
{{ template "nxpod.builtinRegistry.name" $ }}
{{- else -}}
{{ $comp.registry.name }}
{{- end -}}
{{- end -}}

{{- if not $comp.disabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-builder-config
  labels:
    app: {{ template "nxpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  image-builder.json: |-
    {
        "builder": {
            {{- if $comp.registry.secretName -}}"dockerCfgFile": "/config/pull-secret.json",{{- end -}}
            "nxpodLayerLoc": "/app/workspace-image-layer.tar.gz",
            "baseImageRepository": "{{ or $comp.registry.baseImageName (print (include "registry-name" $this) "/base-images") }}",
            "workspaceImageRepository": "{{ or $comp.registry.workspaceImageName (print (include "registry-name" $this) "/workspace-images") }}",
            "imageBuildSalt": "{{ $comp.imageBuildSalt | default "" }}"
        },
        "refCache": {
            "interval": "6h",
            "refs": ["{{ template "nxpod.comp.imageFull" (dict "root" . "gp" $.Values "comp" .Values.components.workspace.defaultImage) }}"]
        },
        "pprof": {
            "address": ":6060"
        },
        "prometheus": {
            "address": ":9500"
        },
        "service": {
            "address": ":8080"
        }
    }
{{- end -}}