# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: node-daemon:node-daemon
  labels:
    app: {{ template "nxpod.fullname" . }}
    component: node-daemon
    kind: role-binding
    stage: {{ .Values.installation.stage }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-daemon
subjects:
- kind: ServiceAccount
  name: node-daemon
