# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: server
  labels:
    app: {{ template "nxpod.fullname" . }}
    component: server
    kind: role-binding
    stage: {{ .Values.installation.stage }}
subjects:
- kind: ServiceAccount
  name: server
roleRef:
  kind: Role
  name: server
  apiGroup: rbac.authorization.k8s.io
