# Copyright (c) 2022 Nxpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

apiVersion: workspace.nxpod.io/v1
kind: Workspace
metadata:
  name: workspace-sample
spec:
