packages:
  - name: installer
    type: yarn
    srcs:
      - package.json
      - "scripts/post-generate.js"
      - "webpack.config.js"
      - "startup.sh"
      - "**/*.ico"
    deps:
      - components/nxpod-protocol:lib
      - components/theia/packages/nxpod-extension:lib
    config:
      packaging: offline-mirror
      dontTest: true
      commands:
        build: ["yarn", "build"]
      yarnLock: ${coreYarnLockBase}/../yarn.lock
  - name: builtin-plugins
    type: generic
    deps:
      - components/nxpod-protocol:theia-plugin-list
    config:
      commands:
        - ["mkdir", "-p", "plugins"]
        - - sh
          - -c
          - cat components-nxpod-protocol--theia-plugin-list/manifest.json | jq -r '.[] | "wget -Oplugins/\(.loc) \(.url)"' | sh
        - ["cp", "components-nxpod-protocol--theia-plugin-list/manifest.json", "plugins/plugins.json"]
  - name: docker
    type: docker
    srcs:
      - "package-libs.sh"
      - "supervisor-config.json"
    deps:
      - :installer
      - :builtin-plugins
      - components/theia/supervisor:app
    argdeps:
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      image:
        - ${imageRepoBase}/theia-ide:${version}
