packages:
  - name: docker
    type: docker
    argdeps:
      - imageRepoBase
      - codeWebExtensionCommit
    config:
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: workspace.codeWebExtensionImage
      buildArgs:
        CODE_EXTENSION_COMMIT: ${codeWebExtensionCommit}
      image:
        - ${imageRepoBase}/ide/nxpod-code-web:${version}
        - ${imageRepoBase}/ide/nxpod-code-web:commit-${__git_commit}
