# debug using `werft run github -f -s .werft/build.js -j .werft/build.yaml -a debug=true`
pod:
  serviceAccount: werft
  nodeSelector:
    cloud.google.com/gke-nodepool: workload
  volumes:
  - name: gcp-sa
    secret:
      secretName: gcp-sa-nxpod-dev-deployer
  - name: gcp-sa-release
    secret:
      secretName: gcp-sa-nxpod-release-deployer
  - name: gcp-sa-nxpod-helmchartregistry
    secret:
      secretName: gcp-sa-nxpod-helmchartregistry-deployer
  # - name: deploy-key
  #   secret:
  #     secretName: deploy-key
  # - name: github-ssh-key
  #   secret:
  #     secretName: github-ssh-key
  #     defaultMode: 0600
  # - name: nxpod-test-tokens
  #   secret:
  #     secretName: nxpod-test-tokens
  containers:
  - name: testdb
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test
    # Using the same port as in our Nxpod workspaces here
    - name: MYSQL_TCP_PORT
      value: 23306
  - name: build
    image: eu.gcr.io/nxpod-core-dev/dev/dev-environment:gpl-improve-core-previews.1
    workingDir: /workspace
    imagePullPolicy: Always
    volumeMounts:
    - name: gcp-sa
      mountPath: /mnt/secrets/gcp-sa
      readOnly: true
    - name: gcp-sa-release
      mountPath: /mnt/secrets/gcp-sa-release
      readOnly: true
    - name: gcp-sa-nxpod-helmchartregistry
      mountPath: /mnt/secrets/gcp-sa-nxpod-helmchartregistry
      readOnly: true
    # - name: deploy-key
    #   mountPath: /mnt/secrets/deploy-key
    #   readOnly: true
    # - name: github-ssh-key
    #   mountPath: /mnt/secrets/github-ssh-key
    #   readOnly: true
    env:
    - name: LEEWAY_WORKSPACE_ROOT
      value: /workspace
    - name: LEEWAY_REMOTE_CACHE_BUCKET
      {{- if eq .Repository.Ref "refs/heads/master" }}
      value: nxpod-core-leeway-cache-master
      {{- else }}
      value: nxpod-core-leeway-cache-branch
      {{- end }}
    - name: GOPROXY
      value: http://athens-athens-proxy.athens.svc.cluster.local:9999
    - name: WERFT_HOST
      value: "werft.werft.svc.cluster.local:7777"
    - name: NODENAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    # - name: NXPOD_TEST_TOKEN_GITHUB
    #   valueFrom:
    #     secretKeyRef:
    #       name: nxpod-test-tokens
    #       key: github-test-token.json
    # - name: NXPOD_TEST_TOKEN_GITLAB
    #   valueFrom:
    #     secretKeyRef:
    #       name: nxpod-test-tokens
    #       key: gitlab-test-token.json
    # - name: NXPOD_TEST_TOKEN_BITBUCKET
    #   valueFrom:
    #     secretKeyRef:
    #       name: nxpod-test-tokens
    #       key: bitbucket-test-token.json
    command:
      - bash 
      - -c
      - |
        sleep 1
        set -Eeuo pipefail

        export DOCKER_HOST=tcp://$NODENAME:2375
        sudo chown -R nxpod:nxpod /workspace

        npm install shelljs
        printf '{{ toJson . }}' > context.json

        {{- if .Annotations.debug }}
        node --inspect-brk .werft/build.js
        {{- else }}
        node --inspect .werft/build.js
        {{- end }}
sidecars:
- testdb