{
 "title": "Node Pressure Stall Information",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(nxpod_ws_manager_mk2_workspace_phase_total, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_pressure_memory_waiting_seconds_total,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workspace node's normalized Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$cluster: Workspace node's normalized load average",
   "type": "graph",
   "description": "Nodes with a high normalized load average do not represent a real problem, it only means that pods should probably not be scheduled to them.\n\nIf you'd like to see more details about resource consumption of a particular node, you can do so by clicking at the node name.\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(nodepool:node_load1:normalized{cluster=~\"$cluster\", nodepool=~\".*workspace.*\", node=~\"$node\"}) by (node))\n",
     "legendFormat": "{{node}}"
    },
    { "expr": "1\n", "legendFormat": "Node Max Load Avg" }
   ]
  },
  {
   "title": "Workspace node's cpu pressure stall information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "$cluster: Workspace node's cpu pressure stall information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "topk(5, rate(node_pressure_cpu_waiting_seconds_total{cluster=\"$cluster\",node=~\"$node\"}[30s]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Workspace node's memory pressure stall information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "$cluster: Workspace node's memory pressure stall information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "topk(5, rate(node_pressure_memory_waiting_seconds_total{cluster=\"$cluster\",node=~\"$node\"}[30s]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Workspace node's IO pressure stall information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "$cluster: Workspace node's IO pressure stall information",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "topk(5, rate(node_pressure_io_waiting_seconds_total{cluster=\"$cluster\",node=~\"$node\"}[30s]))",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}