{{ if eq .Values.jaeger.storage "elasticsearch" -}}
apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  labels:
    app: jaeger
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}