{
 "title": "SSH Gateway Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nxpod_ws_proxy_ssh_attempt_total{error_type!~\"OTHERS|WS_ID_INVALID\"}[2m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Suspicious attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (error_type) (rate(nxpod_ws_proxy_ssh_attempt_total{error_type=~\"OTHERS|WS_ID_INVALID\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nxpod_ws_proxy_ssh_attempt_total{error_type!~\"WS_ID_INVALID|OTHERS\",status=\"failed\"}[2m]))/sum(rate(nxpod_ws_proxy_ssh_attempt_total{error_type!~\"WS_ID_INVALID|OTHERS\"}[2m]))",
     "legendFormat": "total ratio"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (error_type) (rate(nxpod_ws_proxy_ssh_attempt_total{error_type!~\"WS_ID_INVALID|OTHERS\",status=\"failed\"}[2m]))/sum(rate(nxpod_ws_proxy_ssh_attempt_total{error_type!~\"WS_ID_INVALID|OTHERS\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}