# Default values for sweeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/nxpod-core-dev/dev/sweeper
  pullPolicy: Always

command: ""

serviceAccountName: server

securityContext:
  privileged: false
  runAsUser: 1000

imagePullSecrets:
- name: workspace-registry-pull-secret

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: nxpod.io/workload_meta
              operator: In
              values:
                - 'true'