# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

nxpod:
  db:
    host: db
    port: 3306
    password: your-password-goes-here

  mysql:
    enabled: false