# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

nxpod:
  # workspaceSizing configures the resources available to each workspace. These settings directly impact how
  # desenly we pack workspaces on nodes where workspacesPerNode = memoryAvailable(node) / memoryRequest.
  #
  # Beware: if a workspace exceeds its memoryLimit, some of its processes may be terminated (OOM-kill) which
  # results in a broken user experience.
  workspaceSizing:
    requests:
      cpu: "1m"
      memory: "2.25Gi"
      storage: "5Gi"
    limits:
      cpu: "5"
      memory: "12Gi"