packages:
  - name: lib
    type: yarn
    srcs:
      - "src/**"
      - package.json
    deps:
      - components/nxpod-protocol:lib
    config:
      packaging: library
      yarnLock: ${coreYarnLockBase}/yarn.lock
      tsconfig: tsconfig.json
      dontTest: true
  - name: docker
    type: docker
    srcs:
      - configure.sh
    argdeps:
      - imageRepoBase
    config:
      dockerfile: Dockerfile
      image:
        - ${imageRepoBase}/messagebus:${version}
        - ${imageRepoBase}/messagebus:${__pkg_version}
