# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

apiVersion: v1
kind: Pod
metadata:
  name: nxpod-helm-installer
spec:
    containers:
      - name: nxpod-helm-installer
        image: alpine/helm:3.2.4
        volumeMounts:
          - name: kubeconfig
            mountPath: /root/.kube/config
          - name: installfiles
            mountPath: /root/install
          - name: chart
            mountPath: /root/chart
        command: ["sh", "/root/install/command.sh"]
    volumes:
      - name: kubeconfig
        hostPath:
          path: /etc/rancher/k3s/k3s_.yaml
      - name: installfiles
        configMap:
          name: nxpod-helm-installer
      - name: chart
        hostPath:
          path: /chart
    restartPolicy: OnFailure

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nxpod-helm-installer
data:
  command.sh: |-
    #!/bin/sh
    set -eux

    echo ""
    echo "values.yaml file:"
    cat /root/install/values.yaml
    echo ""

    if [ -z "$(ls /root/chart)" ]; then
      echo "Installing Nxpod from charts.nxpod.io"
      helm repo add nxpod https://charts.nxpod.io
      helm repo update
      helm install nxpod nxpod/nxpod --timeout 60m --version "$NXPOD_CHART_VERSION" --values /root/install/values.yaml
    else
      echo "Installing Nxpod from local chart folder"
      cd /root/chart
      helm dependency update
      helm install nxpod . --timeout 60m --values /root/install/values.yaml
    fi
    
    echo ""
    echo "Done"
  values.yaml: |-
    # values.yaml added by Docker entrypoint.sh
