# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{- $comp := .Values.nxpod.components.server -}}
{{- if $comp.storage.keyFilePath }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-server-storage-key
  labels:
    app: {{ template "nxpod.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  "{{ base $comp.storage.keyFilePath }}": {{ $.Files.Get $comp.storage.keyFilePath | b64enc | quote }}
{{- end }}