{
 "title": "Nxpod / Component / ws-daemon",
 "tags": [ "nxpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"ws-daemon\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"ws-daemon.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"ws-daemon.*\"}, pod)"
    }
   },
   {
    "name": "grpc_method",
    "label": "gRPC Method",
    "query": {
     "query": "label_values(grpc_server_handled_total{job=\"ws-daemon\", cluster=~\"$cluster\"}, grpc_method)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(workqueue_depth{pod=~\"$pod\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(rate(workqueue_adds_total{job=\"ws-daemon\", pod=~\"$pod\", name=~\"$controller\"}[5m])) by (cluster, pod, name))",
     "legendFormat": "{{cluster}} - {{pod}} - {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(workqueue_depth{job=\"ws-daemon\", cluster=~\"$cluster\", name=~\"$controller\"}) by (cluster, pod, name))",
     "legendFormat": "{{cluster}} - {{pod}} - {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_queue_duration_seconds_bucket{job=\"ws-daemon\", pod=~\"$pod\", name=~\"$controller\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-daemon\", pod=~\"$pod\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-daemon\", pod=~\"$pod\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-daemon\", pod=~\"$pod\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"ws-daemon\", pod=~\"$pod\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20, sum(rate(controller_runtime_reconcile_total{job=\"ws-daemon\", pod=~\"$pod\", controller=~\"$controller\"}[5m])) by (cluster, pod, controller, result))",
     "legendFormat": "{{cluster}} - {{pod}} - {{controller}} - {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Work Duration",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_work_duration_seconds_bucket{job=\"ws-daemon\", pod=~\"$pod\", name=~\"$controller\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Longest running reconciliation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(20, max(workqueue_longest_running_processor_seconds{job=\"ws-daemon\", pod=~\"$pod\", name=~\"$controller\"}) by (cluster, pod, name))",
     "legendFormat": "{{cluster}} - {{pod}} - {{name}}"
    }
   ]
  },
  {
   "title": "gRPC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "gRPC calls handled (Server-side)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[1m])) by (grpc_code, grpc_method, cluster)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - {{grpc_code}}"
      }
     ]
    },
    {
     "title": "gRPC start and finish rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_started_total{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[1m])) by (grpc_code, grpc_method, cluster)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - Started"
      },
      {
       "expr": "sum(rate(grpc_server_handled_total{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[1m])) by (grpc_method, cluster)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - Finished"
      }
     ]
    },
    {
     "title": "$grpc_method: Time handling gRPC calls",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
     "repeat": "grpc_method",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, \n  sum(\n    rate(grpc_server_handling_seconds_bucket{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method, le)\n)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - 99th Percentile"
      },
      {
       "expr": "histogram_quantile(0.95, \n  sum(\n    rate(grpc_server_handling_seconds_bucket{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method, le)\n)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - 95th Percentile"
      },
      {
       "expr": "histogram_quantile(0.50, \n  sum(\n    rate(grpc_server_handling_seconds_bucket{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=~\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method, le)\n)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - 50th Percentile"
      },
      {
       "expr": "  sum(\n    rate(grpc_server_handling_seconds_sum{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method)\n  /\n  sum(\n    rate(grpc_server_handling_seconds_count{job=\"ws-daemon\", cluster=~\"$cluster\", grpc_method=\"$grpc_method\"}[5m])\n  ) by (cluster, grpc_method)",
       "legendFormat": "{{cluster}} - {{grpc_method}} - avg"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container image version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kube_pod_container_info{cluster=~\"$cluster\", pod=~\"$pod\", image=~\".+\", container=\"ws-daemon\"}",
     "legendFormat": "{{cluster}} - {{image}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Cores being used"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "description": "Saturation > 100% means that the container is requesting more than its limits.\n\nKubernetes will start to throttle CPU when that happens. That's a sign of degraded performance.\n\n'No Data' indicates that the pod has no CPU limits.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node} - {{pod}} - CPU Saturation"
    },
    {
     "expr": "sum(\nrate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod)",
     "legendFormat": "{{pod}} - CPU Throttles"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "description": "Memory can't be throttled. When a container reaches 100% of its memory limits,  Kubernetes will kill the container and restart it.\n\n'No Data' indicates that the pod doesn't have Memory limits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\nrate(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\", resource=\"memory\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Memory Saturation"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Network Saturation (Packets Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Receive"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{cluster}} - {{kubernetes_pod_node_name}} - {{pod}} "
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{cluster=~\"$cluster\", pod=~\"$pod\"} == 1 ",
     "legendFormat": "{{pod}}  - RUNNING"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_terminated{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{pod}}  - TERMINATED -> {{reason}}"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_waiting{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{pod}}  - WAITING -> {{reason}}"
    }
   ]
  },
  {
   "title": "Replicas availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_desired_number_scheduled{cluster=~\"$cluster\", daemonset=\"ws-daemon\"}",
     "legendFormat": "{{cluster}} - {{daemonset}} - Desired"
    },
    {
     "expr": "kube_daemonset_status_number_available{cluster=~\"$cluster\", daemonset=\"ws-daemon\"}",
     "legendFormat": "{{cluster}} - {{daemonset}} - Available replicas"
    },
    {
     "expr": "kube_daemonset_status_number_unavailable{cluster=~\"$cluster\", daemonset=\"ws-daemon\"}",
     "legendFormat": "{{cluster}} - {{daemonset}} - Unvailable replicas"
    }
   ]
  },
  {
   "title": "Go Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\"}[5m])",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Allocation rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\"}[5m])",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Garbage collection time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\", quantile=\"0.5\"}",
       "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 50th percentile"
      },
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\", quantile=\"0.75\"}",
       "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 75th percentile"
      },
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"ws-daemon\", pod=~\"$pod\", quantile=\"1\"}",
       "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 100th percentile"
      }
     ]
    }
   ]
  }
 ]
}