# Copyright (c) 2022 Nxpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License.AGPL.txt in the project root for license information.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: login-slo-monitoring-rules
spec:
  groups:
  - name: login-slo-recording-rules
    rules:
    - record: nxpod_server_login_requests_total:5m_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[5m]))
        /
        sum(rate(nxpod_server_login_requests_total[5m]))

    - record: nxpod_server_login_requests_total:30m_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[30m]))
        /
        sum(rate(nxpod_server_login_requests_total[30m]))

    - record: nxpod_server_login_requests_total:1h_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[1h]))
        /
        sum(rate(nxpod_server_login_requests_total[1h]))

    - record: nxpod_server_login_requests_total:2h_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[2h]))
        /
        sum(rate(nxpod_server_login_requests_total[2h]))

    - record: nxpod_server_login_requests_total:6h_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[6h]))
        /
        sum(rate(nxpod_server_login_requests_total[6h]))

    - record: nxpod_server_login_requests_total:1d_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[1d]))
        /
        sum(rate(nxpod_server_login_requests_total[1d]))

    - record: nxpod_server_login_requests_total:3d_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[3d]))
        /
        sum(rate(nxpod_server_login_requests_total[3d]))

    - record: nxpod_server_login_requests_total:30d_failure_ratio
      expr: |
        sum(rate(nxpod_server_login_requests_total{status="failed"}[30d]))
        /
        sum(rate(nxpod_server_login_requests_total[30d]))

    - record: nxpod_server_login_requests_total:slo_target
      expr: "0.95"

    - record: nxpod_server_login_requests_total:error_budget_remaining
      expr: nxpod_server_login_requests_total:monthly_availability - nxpod_server_login_requests_total:slo_target

    - record: nxpod_server_login_requests_total:monthly_availability
      expr: 1 - nxpod_server_login_requests_total:30d_failure_ratio

  - name: login-slo-alerts
    rules:
    - alert: NxpodLoginErrorBudgetBurn
      labels:
        severity: critical
      annotations:
        runbook_url: https://github.com/nxpod-com/observability/blob/main/runbooks/NxpodLoginErrorBudgetBurn.md
        summary: Error budget is being burn too quickly.
        description: Error budget is being burn too quickly. At this rate, the whole monthly budget will be burnt in less than 2 days.
      expr: |
        (
          nxpod_server_login_requests_total:1h_failure_ratio > (14.4 * (1 - nxpod_server_login_requests_total:slo_target))
          and
          nxpod_server_login_requests_total:5m_failure_ratio > (14.4 * (1 - nxpod_server_login_requests_total:slo_target))
        )
        or
        (
          nxpod_server_login_requests_total:6h_failure_ratio > (6 * (1 - nxpod_server_login_requests_total:slo_target))
          and
          nxpod_server_login_requests_total:30m_failure_ratio > (6 * (1 - nxpod_server_login_requests_total:slo_target))
        )

    - alert: NxpodLoginErrorBudgetBurn
      labels:
        severity: warning
      annotations:
        runbook_url: https://github.com/nxpod-com/observability/blob/main/runbooks/NxpodLoginErrorBudgetBurn.md
        summary: Error budget is being burn quickly.
        description: Error budget is being burn quickly. At this rate, the whole monthly budget will be burnt in less than 10 days.
      expr: |
        (
          nxpod_server_login_requests_total:1d_failure_ratio > (3 * (1 - nxpod_server_login_requests_total:slo_target))
          and
          nxpod_server_login_requests_total:2h_failure_ratio > (3 * (1 - nxpod_server_login_requests_total:slo_target))
        )
        or
        (
          nxpod_server_login_requests_total:3d_failure_ratio > (1 * (1 - nxpod_server_login_requests_total:slo_target))
          and
          nxpod_server_login_requests_total:6h_failure_ratio > (1 * (1 - nxpod_server_login_requests_total:slo_target))
        )
