# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{- if .Values.nxpod_selfhosted -}}
{{- if .Values.nxpod_selfhosted.variants -}}
{{- if .Values.nxpod_selfhosted.variants.customRegistry -}}
{{ include "nxpod.pull-secret" (dict "root" . "secret" .Values.nxpod.components.imageBuilder.registry) }}
{{- end -}}
{{- end -}}
{{- end -}}