# Copyright (c) 2020 TypeFox GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{- if .Values.nxpod_selfhosted -}}
{{- if .Values.nxpod_selfhosted.variants -}}
{{- if .Values.nxpod_selfhosted.variants.customCerts -}}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-config-certificates
  labels:
    app: {{ template "nxpod.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    checksum/checksd-config: {{ ($.Files.Get .Values.nxpod.certificatesSecret.path) | sha256sum }}
data:
{{ ($.Files.Glob .Values.nxpod.certificatesSecret.path).AsSecrets | nindent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}