packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/common-go:lib
    env:
      - CGO_ENABLED=0
      - GOOS=linux
    config:
      buildFlags:
        - "-ldflags=-w"
  - name: docker
    type: docker
    deps:
      - :app
      - components/theia/app:docker
    argdeps:
      - version
      - imageRepoBase
    config:
      dockerfile: leeway.Dockerfile
      buildArgs:
        BASE: ${imageRepoBase}/theia-ide:${version}
      image:
        - ${imageRepoBase}/theia-server:${version}
