name: Check nxpod.yaml changes
on:
  push:
    paths:
      - ".nxpod.yml"
      - ".github/workflows/check-nxpodyaml.yml"
  pull_request:
    paths:
      - ".nxpod.yml"
      - ".github/workflows/check-nxpodyaml.yml"

jobs:
  notify:
    name: Build and upload model
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
          -X POST -d '{"body": ":warning: Hew reviewer! BE CAREFUL :warning: \n Review the code before opening in your Nxpod. .nxpod.yaml was changed and it might be harfmul."}' \
          "https://api.github.com/repos/khulnasoft/nxpod/issues/${pull_number}/comments"
