name: Check nxpod.yaml changes
on:
  pull_request:
    paths:
      - ".nxpod.yml"
      - ".github/workflows/check-nxpodyaml.yml"

jobs:
  notify:
    name: Build and upload model
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: ${{ github.event.pull_request.number }}
          comment: |
            :warning: Hey reviewer! BE CAREFUL :warning:
            Review the code before opening in your Nxpod. `.nxpod.yml` was changed and it might be harmful.
